### ISSUE TITLE
[Question] Run node-omxplayer on mac?

### ISSUE THREAD

**Issue by Jones-S** [Ap0c/node-omxplayer#12]
Is there any way to run this player not on my raspberry but on my mac?
I would like to change something to the code and for testing purposes this would be ideal.

For now, if I run a javascript file, which uses the node-omxplayer it says I don't have the underlying [OMX Player](https://github.com/popcornmix/omxplayer) installed – which I actually don't. But I cannot figure out how to do that. Is it even possible to run it on a mac?

**Comment by rip3rs** [comment]
Hmm, that would not be possible to use omxplayer on a mac as it is specifically based for ARM cpu's. I dont't believe there are codecs or drivers for omxplayer for mac. You could however use VLC or other players out there.

**Comment by Jones-S** [comment]
Ok. Thx that's all I wanted to know. I don't need VLC. I just wanted to debug the raspberry code without deploying it.
