### ISSUE TITLE
The close event gets called multiple times

### ISSUE THREAD

**Issue by IvandeWolf** [Ap0c/node-omxplayer#13]
I listen to the close event to do something after a video is finished playing.

After first time adding a newSource and when the video is done the close event is called once (this is good).
But when I play a second video by adding newSource and when the video is done the close event is called twice.
And after a third video the close event is called three times.

Is there a reason this happens?

**Comment by GeorgianStan** [comment]
The problem may be in your code. 
You probabily have registered the event ('on - close') more than one time.
I had the same problem.
I used sockets and inside the connection method from socket.io I had registered the .on('close') method
So each time I've refreshed the browser a new on close even was registered.
Place that even outside of any other functions

**Comment by IvandeWolf** [comment]
That's a good call! I use socket.io too so I am going to check that and I will let you know if that is indeed the cause.
